### PR TITLE
Jasonmacgowan/project config

### PR DESCRIPTION
**Pull request by jasonmacgowan**
### Summary of changes

- implement form update
- use dotenv to parse existing configs instead of homegrown
- read `.env` and `.env.example`
- render config editor from `variables.yml` instead of interpreting the contents of the `.env*` files
- style changes to the form

### Todo

- [ ] Script to generate `.env.example` from `variables.yml`
- [ ] Tests! Tests! Tests!
- [ ] Render inputs differently based on config type (handlebars helper)
   - [ ] Select box for enums
   - [ ] Checkbox for true/false

### CODE REVIEW

**Comment by jasonmacgowan** [comment]
@primetheus I just added the description as a tooltip.  Could use a hand filling in and TODO in https://github.com/github/rally/pull/124/files#diff-c04633407cd5532701421f73dc9de118

**Comment by jasonmacgowan** [comment]
@primetheus I think we're in a good spot now to give it a good test.  Before we ship it we need to add CSRF protection.

**Review by primetheus — APPROVED** [review]

**Comment by primetheus** [comment]
@jasonmacgowan this look pretty good! I have a couple of observations:

1. It seems to presently start off the screen, and I can't scroll up. 



2. perhaps not for this PR, but the SSH key would be good as an `Upload` type.

3. Since we support username/password _or_ token, maybe we should have a radio button to select between the two, and then reveal the input field based on that?

I think for a first iteration only #1 really matters

**Comment by jasonmacgowan** [comment]
Deprecated in favor of https://github.com/github/rally/pull/140

**Pull request closed without merging**
